version: '3.5'

services:
  api:
    build: 
      context: .
      dockerfile: ./build/Dockerfile
    restart: unless-stopped
    ports:
    - 8080:8080
    environment:
      DATABASE_DSN: "postgres://user:user@postgres:5432/transactions-service?sslmode=disable"
      DATABASE_NAME: "transactions-service"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      PGDATA: /data/postgres
      POSTGRES_DB: transactions-service
    volumes:
      - pg-data4:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  pg-data4: {}